#datasource:
#  db:
#    default: ${APP_ENV}
#    development:
#      username: ""
#      password: ""
#      url: jdbc:h2:./database
#    production:
#      username: ${JDBC_DATABASE_USERNAME}
#      password: ${JDBC_DATABASE_PASSWORD}
#      url: ${JDBC_DATABASE_URL}
##  db:
##    username: ""
##    password: ""
##    url: jdbc:h2:./database
#h2:
#  console:
#    path: /h2-console
#    settings:
#      web-allow-others: true
#ebean:
##  db:
##    ddl:
##      run: true
##      generate: true
##      seedSql: seed.sql
#  migration:
#    run: true
datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./database"
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

ebean:
  ddl:
    run: true
    generate: true
    #    seedSql: seed.sql
    migration:
      run: true